# Run all notebooks in the project

test with the new organization

In [17]:
#import library 
import pandas as pd

#read csv file
df = pd.read_csv(
"C:/Users/Anaëlle/Desktop/Stage CHU/AKAKPOVI.ANAELLE/Soutenance_Python/data/REFLEXION.csv",
sep=","
)

#print results
print(df.head())
print(df.shape)
print(df.columns[:10])
print(df["sid"])

       sid  cisdrc  cinouv  cidiag  ciconsent  cisecu  ciage  cnitrbl  cniavc  \
0  C01P001       1       1       1          1       1      1        0       0
1  C01P002       1       1       1          1       1      1        0       0
2  C01P003       1       1       1          1       1      1        0       0
3  C01P004       1       1       1          1       1      1        0       0
4  C01P005       1       1       1          1       1      1        0       0

   cnimoca  ...  v20_css9  v20_pgic  v20_eq_mob  v20_eq_auto  v20_eq_act  \
0        0  ...       1.0       3.0         1.0          1.0         2.0
1        0  ...       1.0       3.0         1.0          2.0         2.0
2        0  ...       1.0       3.0         1.0          1.0         2.0
3        0  ...       NaN       NaN         NaN          NaN         NaN
4        0  ...       1.0       3.0         1.0          1.0         2.0

   v20_eq_doul  v20_eq_anx  v20_eq_sante  femotif         dfe
0          0.0         2.0          40.0        1  2023-11-23
1          0.0         2.0          70.0        1  2024-02-09
2          0.0         2.0          50.0        1  2024-03-22
3          NaN         NaN           NaN        4  2024-10-17
4          0.0         1.0          53.0        1  2025-01-30

[5 rows x 2414 columns]
(7, 2414)
Index(['sid', 'cisdrc', 'cinouv', 'cidiag', 'ciconsent', 'cisecu', 'ciage',
       'cnitrbl', 'cniavc', 'cnimoca'],
      dtype='object')
0    C01P001
1    C01P002
2    C01P003
3    C01P004
4    C01P005
5    C01P006
6    C01P007
Name: sid, dtype: object

In [18]:
#remove index line 3 and reset/reinitialize index
df = df.drop(df.index[3]).reset_index(drop=True)

# select columns with "css" 
df_css = df.filter(regex='css', axis=1)

# show first lines
print(df_css.head())

   icss_rea  icssdoul_s  icsshypall_s  icsshypallp_s  icsstemp_s  icsstempp_s  \
0         1         0.0           6.8            1.0        32.5          1.0
1         1         0.0           4.3            0.0        25.2          0.0
2         1         1.0           3.1            0.0        19.7          0.0
3         1         0.5           5.0            0.0        28.1          0.0
4         1         0.0           3.6            1.0        30.1          1.0

   icsssud_s  icssoed_s  icssoedp_s  icssforce1_s  ...  v20_cssforcescref  \
0       40.0       35.5         1.0          20.1  ...                7.5
1       39.0       38.9         0.0          23.6  ...               25.2
2       37.0       45.7         0.0          43.1  ...               44.8
3       28.0       41.3         0.0          30.0  ...               27.6
4       38.0       38.1         1.0          26.0  ...               25.3

   v20_css1  v20_css2  v20_css3  v20_css4  v20_css5  v20_css6  v20_css7  \
0       1.0       1.0       1.0       1.0       0.0       1.0       1.0
1       NaN       1.0       1.0       1.0       1.0       1.0       1.0
2       1.0       0.0       0.0       1.0       1.0       1.0       1.0
3       1.0       1.0       1.0       0.0       0.0       1.0       0.0
4       1.0       1.0       1.0       1.0       1.0       1.0       0.0

   v20_css8  v20_css9
0       0.0       1.0
1       1.0       1.0
2       1.0       1.0
3       0.0       1.0
4       1.0       1.0

[5 rows x 475 columns]

In [19]:
# Remove columns with "rea" and columns finish by "css1"
df_css_clean = df_css.filter(regex='^(?!.*rea)(?!.*css1$)', axis=1)


# Keep columns that start with "v"              
df_v = df_css_clean.filter(regex='^v', axis=1)

# Remove columns "v" with cssforce1, cssforce2, cssforce3 or cssforcescref
df_v = df_v.filter(regex='^(?!.*cssforce([123]|scref)).*', axis=1)

# Reset index
df_v = df_v.reset_index(drop=True)

# Keep 3 columns "icsstemp_s", "icsssud_s", "icssforcemoy_s"
df_exceptions = df_css_clean.filter(items=["icsstemp_s", "icsssud_s", "icssforcemoy_s"])
df_exceptions = df_exceptions.reset_index(drop=True)

# Combine
df_css_clean = pd.concat([df_v, df_exceptions], axis=1)

#see results
print(df_css_clean.shape)
print(df_css_clean.columns)
print(df_css_clean.head())

(6, 323)
Index(['v1_cssdoul', 'v1_csshypall', 'v1_csstemp', 'v1_csseryth', 'v1_csssud',
       'v1_cssoed', 'v1_csstroph', 'v1_cssforcemoy', 'v1_css2', 'v1_css3',
       ...
       'v20_css3', 'v20_css4', 'v20_css5', 'v20_css6', 'v20_css7', 'v20_css8',
       'v20_css9', 'icsstemp_s', 'icsssud_s', 'icssforcemoy_s'],
      dtype='object', length=323)
   v1_cssdoul  v1_csshypall  v1_csstemp  v1_csseryth  v1_csssud  v1_cssoed  \
0         7.3           1.0         0.0          1.0       34.0        0.0
1         9.8           1.0         1.0          1.0       47.8        1.0
2         2.0           1.0         0.0          0.0       46.5        1.0
3         7.5           1.0         1.0          1.0       59.6        0.0
4         3.5           1.0         0.0          1.0       28.9        0.0

   v1_csstroph  v1_cssforcemoy  v1_css2  v1_css3  ...  v20_css3  v20_css4  \
0          0.0             4.9      1.0      1.0  ...       1.0       1.0
1          0.0             0.0      1.0      1.0  ...       1.0       1.0
2          0.0            13.3      0.0      0.0  ...       0.0       1.0
3          0.0            22.7      1.0      1.0  ...       1.0       0.0
4          1.0             5.9      1.0      1.0  ...       1.0       1.0

   v20_css5  v20_css6  v20_css7  v20_css8  v20_css9  icsstemp_s  icsssud_s  \
0       0.0       1.0       1.0       0.0       1.0        32.5       40.0
1       1.0       1.0       1.0       1.0       1.0        25.2       39.0
2       1.0       1.0       1.0       1.0       1.0        19.7       37.0
3       0.0       1.0       0.0       0.0       1.0        28.1       28.0
4       1.0       1.0       0.0       1.0       1.0        30.1       38.0

   icssforcemoy_s
0            20.5
1            25.2
2            44.8
3            27.7
4            25.6

[5 rows x 323 columns]

In [20]:
#see clean table
df_css_clean

,v1_cssdoul,v1_csshypall,v1_csstemp,v1_csseryth,v1_csssud,v1_cssoed,v1_csstroph,v1_cssforcemoy,v1_css2,v1_css3,...,v20_css3,v20_css4,v20_css5,v20_css6,v20_css7,v20_css8,v20_css9,icsstemp_s,icsssud_s,icssforcemoy_s
0,7.3,1.0,0.0,1.0,34.0,0.0,0.0,4.9,1.0,1.0,...,1.0,1.0,0.0,1.0,1.0,0.0,1.0,32.5,40.0,20.5
1,9.8,1.0,1.0,1.0,47.8,1.0,0.0,0.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,25.2,39.0,25.2
2,2.0,1.0,0.0,0.0,46.5,1.0,0.0,13.3,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,19.7,37.0,44.8
3,7.5,1.0,1.0,1.0,59.6,0.0,0.0,22.7,1.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,28.1,28.0,27.7
4,3.5,1.0,0.0,1.0,28.9,0.0,1.0,5.9,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,1.0,1.0,30.1,38.0,25.6
5,7.0,0.0,0.0,1.0,35.2,0.0,1.0,8.3,1.0,1.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,31.3,34.0,17.0

In [21]:
# New DataFrame for binarisation
binarisation = df_css_clean.copy()

# Select columns with "cssdoul"
colonnes_cssdoul = binarisation.filter(regex='cssdoul', axis=1).columns

# Apply binairy transformation : >=8 -> 1, <8 -> 0
binarisation[colonnes_cssdoul] = binarisation[colonnes_cssdoul].applymap(
    lambda x: 1 if x >= 8 else (0 if pd.notna(x) else pd.NA)
)
# Preview
print("Colonnes transformées en binaire :", list(colonnes_cssdoul))
print(binarisation[colonnes_cssdoul].head())

Colonnes transformées en binaire : ['v1_cssdoul', 'v2_cssdoul', 'v3_cssdoul', 'v4_cssdoul', 'v5_cssdoul', 'v6_cssdoul', 'v7_cssdoul', 'v8_cssdoul', 'v9_cssdoul', 'v10_cssdoul', 'v11_cssdoul', 'v12_cssdoul', 'v13_cssdoul', 'v14_cssdoul', 'v15_cssdoul', 'v16_cssdoul', 'v17_cssdoul', 'v18_cssdoul', 'v19_cssdoul', 'v20_cssdoul']
   v1_cssdoul v2_cssdoul v3_cssdoul  v4_cssdoul  v5_cssdoul  v6_cssdoul  \
0           0          0          0           0           0           0
1           1          1       <NA>           1           1           1
2           0          0          0           0           0           0
3           0       <NA>          1           1           0           0
4           0          0          0           0           0           0

  v7_cssdoul  v8_cssdoul  v9_cssdoul  v10_cssdoul  v11_cssdoul v12_cssdoul  \
0          0           0           0            0            0           0
1          1           1           1            1            1           1
2          0           0           0            0            0           0
3       <NA>           1           1            0            0        <NA>
4          0           0           0            0            0           0

   v13_cssdoul v14_cssdoul  v15_cssdoul  v16_cssdoul  v17_cssdoul  \
0            0        <NA>            0            0            0
1            1           1            0            0            0
2            0           0            0            0            0
3            0           0            0            0            0
4            0           0            0            0            0

   v18_cssdoul  v19_cssdoul  v20_cssdoul
0            0            0            0
1            0            1            0
2            0            0            0
3            1            0            0
4            0            0            0

C:\Users\Anaëlle\AppData\Local\Temp\ipykernel_8656\2822318078.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  binarisation[colonnes_cssdoul] = binarisation[colonnes_cssdoul].applymap(

In [22]:
#csstemp already binarize
colonnes_csstemp = df_css_clean.filter(regex='csstemp', axis=1).columns
print(list(colonnes_csstemp))
# View five first lines csstemp
print(df_css_clean[colonnes_csstemp].head())

['v1_csstemp', 'v2_csstemp', 'v3_csstemp', 'v4_csstemp', 'v5_csstemp', 'v6_csstemp', 'v7_csstemp', 'v8_csstemp', 'v9_csstemp', 'v10_csstemp', 'v11_csstemp', 'v12_csstemp', 'v13_csstemp', 'v14_csstemp', 'v15_csstemp', 'v16_csstemp', 'v17_csstemp', 'v18_csstemp', 'v19_csstemp', 'v20_csstemp', 'icsstemp_s']
   v1_csstemp  v2_csstemp  v3_csstemp  v4_csstemp  v5_csstemp  v6_csstemp  \
0         0.0         0.0         1.0         1.0         0.0         1.0
1         1.0         1.0         NaN         0.0         1.0         0.0
2         0.0         1.0         1.0         1.0         1.0         1.0
3         1.0         NaN         1.0         1.0         0.0         1.0
4         0.0         1.0         1.0         1.0         0.0         0.0

   v7_csstemp  v8_csstemp  v9_csstemp  v10_csstemp  ...  v12_csstemp  \
0         1.0         1.0         1.0          1.0  ...          1.0
1         0.0         1.0         0.0          1.0  ...          1.0
2         1.0         1.0         1.0          1.0  ...          1.0
3         NaN         1.0         0.0          1.0  ...          NaN
4         0.0         1.0         1.0          1.0  ...          1.0

   v13_csstemp  v14_csstemp  v15_csstemp  v16_csstemp  v17_csstemp  \
0          1.0          NaN          1.0          1.0          1.0
1          0.0          1.0          1.0          1.0          0.0
2          1.0          1.0          1.0          1.0          1.0
3          1.0          1.0          1.0          1.0          0.0
4          1.0          1.0          0.0          1.0          1.0

   v18_csstemp  v19_csstemp  v20_csstemp  icsstemp_s
0          1.0          1.0          1.0        32.5
1          1.0          1.0          0.0        25.2
2          1.0          1.0          1.0        19.7
3          1.0          1.0          1.0        28.1
4          0.0          1.0          1.0        30.1

[5 rows x 21 columns]

In [23]:
# Select columns with "csssud" to check values
colonnes_csssud = df_css_clean.filter(regex='csssud', axis=1).columns
print("Colonnes csssud :", list(colonnes_csssud))
# View five first lines
print(df_css_clean[colonnes_csssud].head())

Colonnes csssud : ['v1_csssud', 'v2_csssud', 'v3_csssud', 'v4_csssud', 'v5_csssud', 'v6_csssud', 'v7_csssud', 'v8_csssud', 'v9_csssud', 'v10_csssud', 'v11_csssud', 'v12_csssud', 'v13_csssud', 'v14_csssud', 'v15_csssud', 'v16_csssud', 'v17_csssud', 'v18_csssud', 'v19_csssud', 'v20_csssud', 'icsssud_s']
   v1_csssud  v2_csssud  v3_csssud  v4_csssud  v5_csssud  v6_csssud  \
0       34.0       36.7       45.3       40.0       48.7       46.3
1       47.8       43.5        NaN       42.5       44.3       45.5
2       46.5       44.4       37.1       40.3       36.7       38.3
3       59.6        NaN       46.7       38.8       57.7       55.7
4       28.9       37.8       41.3       39.9       37.6       52.0

   v7_csssud  v8_csssud  v9_csssud  v10_csssud  ...  v12_csssud  v13_csssud  \
0       48.6       32.4       41.0        42.3  ...        41.8        43.8
1       39.4       42.4       40.1        38.1  ...        34.5        40.7
2       43.0       41.7       39.7        39.2  ...        40.7        40.7
3        NaN       54.9       53.8        48.7  ...         NaN        51.8
4       43.6       37.3       39.4        53.6  ...        48.1        41.5

   v14_csssud  v15_csssud  v16_csssud  v17_csssud  v18_csssud  v19_csssud  \
0         NaN        43.6        41.8        40.5        43.4        42.0
1        36.3        38.3        35.0        42.7        36.0        43.7
2        39.7        31.0        42.3        37.7        42.3        40.3
3        49.3        44.6        48.5        40.6        44.7        41.9
4        44.2        49.6        40.8        41.6        40.2        39.2

   v20_csssud  icsssud_s
0        47.0       40.0
1        45.3       39.0
2        40.0       37.0
3        33.2       28.0
4        46.1       38.0

[5 rows x 21 columns]

In [24]:
#check data for "cssoed" already binarized

#Columns with cssoed
colonnes_cssoed = df_css_clean.filter(regex='cssoed', axis=1).columns
print("Colonnes cssoed :", list(colonnes_cssoed))

#view results
print("\nAperçu des colonnes cssoed :")
print(df_css_clean[colonnes_cssoed].head())

Colonnes cssoed : ['v1_cssoed', 'v2_cssoed', 'v3_cssoed', 'v4_cssoed', 'v5_cssoed', 'v6_cssoed', 'v7_cssoed', 'v8_cssoed', 'v9_cssoed', 'v10_cssoed', 'v11_cssoed', 'v12_cssoed', 'v13_cssoed', 'v14_cssoed', 'v15_cssoed', 'v16_cssoed', 'v17_cssoed', 'v18_cssoed', 'v19_cssoed', 'v20_cssoed']

Aperçu des colonnes cssoed :
   v1_cssoed  v2_cssoed  v3_cssoed  v4_cssoed  v5_cssoed  v6_cssoed  \
0        0.0        1.0        1.0        0.0        1.0        1.0
1        1.0        1.0        NaN        1.0        1.0        1.0
2        1.0        1.0        0.0        1.0        0.0        1.0
3        0.0        NaN        1.0        0.0        1.0        1.0
4        0.0        1.0        0.0        1.0        1.0        1.0

   v7_cssoed  v8_cssoed  v9_cssoed  v10_cssoed  v11_cssoed  v12_cssoed  \
0        1.0        0.0        1.0         1.0         1.0         0.0
1        1.0        1.0        1.0         1.0         1.0         1.0
2        1.0        0.0        1.0         1.0         1.0         1.0
3        NaN        1.0        1.0         1.0         1.0         NaN
4        1.0        1.0        1.0         1.0         0.0         0.0

   v13_cssoed  v14_cssoed  v15_cssoed  v16_cssoed  v17_cssoed  v18_cssoed  \
0         1.0         NaN         1.0         1.0         1.0         0.0
1         1.0         1.0         1.0         1.0         0.0         1.0
2         1.0         1.0         1.0         1.0         0.0         0.0
3         1.0         1.0         1.0         1.0         1.0         1.0
4         1.0         0.0         1.0         1.0         1.0         0.0

   v19_cssoed  v20_cssoed
0         0.0         1.0
1         1.0         1.0
2         0.0         1.0
3         1.0         1.0
4         0.0         1.0

In [25]:
#check data for "forcemoy" 

# Columns "cssforcemoy"
colonnes_cssforcemoy = df_css_clean.filter(regex='cssforcemoy', axis=1).columns
print("Colonnes cssforcemoy :", list(colonnes_cssforcemoy))

#view results
print("\nAperçu des colonnes cssforcemoy :")
print(df_css_clean[colonnes_cssforcemoy].head())

Colonnes cssforcemoy : ['v1_cssforcemoy', 'v2_cssforcemoy', 'v3_cssforcemoy', 'v4_cssforcemoy', 'v5_cssforcemoy', 'v6_cssforcemoy', 'v7_cssforcemoy', 'v8_cssforcemoy', 'v9_cssforcemoy', 'v10_cssforcemoy', 'v11_cssforcemoy', 'v12_cssforcemoy', 'v13_cssforcemoy', 'v14_cssforcemoy', 'v15_cssforcemoy', 'v16_cssforcemoy', 'v17_cssforcemoy', 'v18_cssforcemoy', 'v19_cssforcemoy', 'v20_cssforcemoy', 'icssforcemoy_s']

Aperçu des colonnes cssforcemoy :
   v1_cssforcemoy  v2_cssforcemoy  v3_cssforcemoy  v4_cssforcemoy  \
0             4.9             4.9             3.0             5.1
1             0.0             0.0             NaN             0.0
2            13.3            16.8            16.3            13.3
3            22.7             NaN            18.8            18.9
4             5.9             6.8             7.7             7.4

   v5_cssforcemoy  v6_cssforcemoy  v7_cssforcemoy  v8_cssforcemoy  \
0             4.6             5.4             8.2             7.6
1             0.0             0.0             0.0             0.0
2            18.6            16.7            23.7            20.6
3            22.0            21.4             NaN            23.5
4             8.2             8.5            10.0            10.4

   v9_cssforcemoy  v10_cssforcemoy  ...  v12_cssforcemoy  v13_cssforcemoy  \
0             9.0              9.7  ...              9.8             10.1
1             0.0              0.0  ...              0.0              0.0
2            20.8             18.4  ...             21.9             21.2
3            19.9             21.5  ...              NaN             23.9
4            10.2             11.1  ...             12.7             11.4

   v14_cssforcemoy  v15_cssforcemoy  v16_cssforcemoy  v17_cssforcemoy  \
0              NaN             11.0             12.3             11.7
1              0.0              0.0              0.0              0.0
2             24.5             20.1             23.3             25.1
3             27.6             25.0             24.9             23.3
4             12.8             12.9              9.6             13.1

   v18_cssforcemoy  v19_cssforcemoy  v20_cssforcemoy  icssforcemoy_s
0             13.9             14.6             13.6            20.5
1              0.0              0.0              0.0            25.2
2             23.3             24.5             20.6            44.8
3             26.4             23.9             24.1            27.7
4             13.0             14.5             15.4            25.6

[5 rows x 21 columns]

In [26]:
#binarisation "sudation" and "force moyenne" 
# pathologic columns "csssud" 30% difference
colonnes_csssud = df_css_clean.filter(regex='^v.*_csssud$', axis=1).columns

# Binarisation 
binarisation_sud = ((df_css_clean[colonnes_csssud].sub(df_css_clean['icsssud_s'], axis=0)
                     .abs()
                     .div(df_css_clean['icsssud_s'], axis=0)) >= 0.3)

binarisation_sud = binarisation_sud.where(df_css_clean[colonnes_csssud].notna()).astype("Int64")

# view
print(binarisation_sud.head())

# pathologic columns "forcemoy"
colonnes_cssforcemoy = df_css_clean.filter(regex='^v.*_cssforcemoy$', axis=1).columns

# Binarisation 5kg difference
binarisation_forcemoy = ((df_css_clean[colonnes_cssforcemoy]
                          .sub(df_css_clean['icssforcemoy_s'], axis=0)
                          .abs()) >= 5)

binarisation_forcemoy = binarisation_forcemoy.where(df_css_clean[colonnes_cssforcemoy].notna()).astype("Int64")
# View
print(binarisation_forcemoy.head())

   v1_csssud  v2_csssud  v3_csssud  v4_csssud  v5_csssud  v6_csssud  \
0          0          0          0          0          0          0
1          0          0       <NA>          0          0          0
2          0          0          0          0          0          0
3          1       <NA>          1          1          1          1
4          0          0          0          0          0          1

   v7_csssud  v8_csssud  v9_csssud  v10_csssud  v11_csssud  v12_csssud  \
0          0          0          0           0           0           0
1          0          0          0           0           0           0
2          0          0          0           0           0           0
3       <NA>          1          1           1           0        <NA>
4          0          0          0           1           0           0

   v13_csssud  v14_csssud  v15_csssud  v16_csssud  v17_csssud  v18_csssud  \
0           0        <NA>           0           0           0           0
1           0           0           0           0           0           0
2           0           0           0           0           0           0
3           1           1           1           1           1           1
4           0           0           1           0           0           0

   v19_csssud  v20_csssud
0           0           0
1           0           0
2           0           0
3           1           0
4           0           0
   v1_cssforcemoy  v2_cssforcemoy  v3_cssforcemoy  v4_cssforcemoy  \
0               1               1               1               1
1               1               1            <NA>               1
2               1               1               1               1
3               1            <NA>               1               1
4               1               1               1               1

   v5_cssforcemoy  v6_cssforcemoy  v7_cssforcemoy  v8_cssforcemoy  \
0               1               1               1               1
1               1               1               1               1
2               1               1               1               1
3               1               1            <NA>               0
4               1               1               1               1

   v9_cssforcemoy  v10_cssforcemoy  v11_cssforcemoy  v12_cssforcemoy  \
0               1                1                1                1
1               1                1                1                1
2               1                1                1                1
3               1                1                0             <NA>
4               1                1                1                1

   v13_cssforcemoy  v14_cssforcemoy  v15_cssforcemoy  v16_cssforcemoy  \
0                1             <NA>                1                1
1                1                1                1                1
2                1                1                1                1
3                0                0                0                0
4                1                1                1                1

   v17_cssforcemoy  v18_cssforcemoy  v19_cssforcemoy  v20_cssforcemoy
0                1                1                1                1
1                1                1                1                1
2                1                1                1                1
3                0                0                0                0
4                1                1                1                1

In [27]:
# Final table based on df_css_clean
df_binarise_final = df_css_clean.copy()

#replace pain columns by binary version 
df_binarise_final[colonnes_cssdoul] = binarisation[colonnes_cssdoul]

#replace "sudation" column by binary version
df_binarise_final[colonnes_csssud] = binarisation_sud

#replace "forcemoy" columns
df_binarise_final[colonnes_cssforcemoy] = binarisation_forcemoy

#delete healthy columns
df_binarise_final = df_binarise_final.drop(
    columns=["icsssud_s", "icssforcemoy_s", "icsstemp_s"],
    errors="ignore"
)

#view clean
df_binarise_final

,v1_cssdoul,v1_csshypall,v1_csstemp,v1_csseryth,v1_csssud,v1_cssoed,v1_csstroph,v1_cssforcemoy,v1_css2,v1_css3,...,v20_csstroph,v20_cssforcemoy,v20_css2,v20_css3,v20_css4,v20_css5,v20_css6,v20_css7,v20_css8,v20_css9
0,0,1.0,0.0,1.0,0,0.0,0.0,1,1.0,1.0,...,1.0,1,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0
1,1,1.0,1.0,1.0,0,1.0,0.0,1,1.0,1.0,...,0.0,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,0,1.0,0.0,0.0,0,1.0,0.0,1,0.0,0.0,...,0.0,1,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
3,0,1.0,1.0,1.0,1,0.0,0.0,1,1.0,1.0,...,1.0,0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0,1.0,0.0,1.0,0,0.0,1.0,1,1.0,1.0,...,1.0,1,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0
5,0,0.0,0.0,1.0,0,0.0,1.0,1,1.0,1.0,...,0.0,1,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0

In [28]:
#export to csv

#define index
df_binarise_final.index = [f"case {i+1}" for i in range(len(df_binarise_final))]

# name the index
df_binarise_final.index.name = "sid"

df_binarise_final.to_csv(
"C:/Users/Anaëlle/Desktop/Stage CHU/AKAKPOVI.ANAELLE/Soutenance_Python/data/df_binarise_final.csv",
sep=";",
encoding="utf-8-sig",
index=True
)

In [29]:
#open csv file df_binarise_final to check lines
df = pd.read_csv(
    "C:/Users/Anaëlle/Desktop/Stage CHU/AKAKPOVI.ANAELLE/Soutenance_Python/data/df_binarise_final.csv",
    sep=';' 
)
#print results
print(df.head())
print(df.shape)

      sid  v1_cssdoul  v1_csshypall  v1_csstemp  v1_csseryth  v1_csssud  \
0  case 1           0           1.0         0.0          1.0          0
1  case 2           1           1.0         1.0          1.0          0
2  case 3           0           1.0         0.0          0.0          0
3  case 4           0           1.0         1.0          1.0          1
4  case 5           0           1.0         0.0          1.0          0

   v1_cssoed  v1_csstroph  v1_cssforcemoy  v1_css2  ...  v20_csstroph  \
0        0.0          0.0               1      1.0  ...           1.0
1        1.0          0.0               1      1.0  ...           0.0
2        1.0          0.0               1      0.0  ...           0.0
3        0.0          0.0               1      1.0  ...           1.0
4        0.0          1.0               1      1.0  ...           1.0

   v20_cssforcemoy  v20_css2  v20_css3  v20_css4  v20_css5  v20_css6  \
0                1       1.0       1.0       1.0       0.0       1.0
1                1       1.0       1.0       1.0       1.0       1.0
2                1       0.0       0.0       1.0       1.0       1.0
3                0       1.0       1.0       0.0       0.0       1.0
4                1       1.0       1.0       1.0       1.0       1.0

   v20_css7  v20_css8  v20_css9
0       1.0       0.0       1.0
1       1.0       1.0       1.0
2       1.0       1.0       1.0
3       0.0       0.0       1.0
4       0.0       1.0       1.0

[5 rows x 321 columns]
(6, 321)

In [30]:
#create table for bland altman 
# copy data frame binarized
df_score = df_binarise_final.copy()

# final table for scores
df_scores = pd.DataFrame(index=df_score.index)

# new table for score 
df_scores = pd.DataFrame(index=df_binarise_final.index)

# Boucle on V1 à V20
for i in range(1, 21):

    # visit columns
    cols_v = df_binarise_final.filter(regex=f'^v{i}_').columns

    # Separate objectif / subjectif
    cols_obj = cols_v[:8]   # 8 premières colonnes
    cols_subj = cols_v[8:]  # 8 dernières colonnes

    # Calculate scores
    df_scores[f'V{i}_Scoreobj'] = df_binarise_final[cols_obj].sum(axis=1)
    df_scores[f'V{i}_Scoresubj'] = df_binarise_final[cols_subj].sum(axis=1)

# final result
print(df_scores.shape)
print(df_scores.head())

df_scores.to_csv(
"C:/Users/Anaëlle/Desktop/Stage CHU/AKAKPOVI.ANAELLE/Soutenance_Python/data/df_scores_final.csv",
sep=";",
encoding="utf-8-sig",
index=True
)

(6, 40)
        V1_Scoreobj  V1_Scoresubj V2_Scoreobj  V2_Scoresubj V3_Scoreobj  \
sid
case 1          3.0           7.0         4.0           7.0         5.0
case 2          6.0           8.0         6.0           8.0           0
case 3          3.0           5.0         3.0           6.0         3.0
case 4          5.0           6.0           0           0.0         7.0
case 5          4.0           6.0         6.0           7.0         4.0

        V3_Scoresubj  V4_Scoreobj  V4_Scoresubj  V5_Scoreobj  V5_Scoresubj  \
sid
case 1           7.0          5.0           7.0          4.0           7.0
case 2           0.0          6.0           8.0          6.0           8.0
case 3           6.0          4.0           6.0          2.0           5.0
case 4           5.0          6.0           4.0          5.0           4.0
case 5           7.0          5.0           7.0          5.0           7.0

        ...  V16_Scoreobj  V16_Scoresubj V17_Scoreobj  V17_Scoresubj  \
sid     ...
case 1  ...           6.0            6.0          5.0            5.0
case 2  ...           6.0            8.0          3.0            8.0
case 3  ...           3.0            6.0          2.0            6.0
case 4  ...           5.0            4.0          4.0            5.0
case 5  ...           6.0            7.0          6.0            7.0

        V18_Scoreobj  V18_Scoresubj  V19_Scoreobj  V19_Scoresubj  \
sid
case 1           3.0            6.0           3.0            6.0
case 2           5.0            8.0           6.0            8.0
case 3           2.0            6.0           3.0            6.0
case 4           6.0            5.0           5.0            4.0
case 5           4.0            7.0           5.0            7.0

        V20_Scoreobj  V20_Scoresubj
sid
case 1           6.0            6.0
case 2           3.0            8.0
case 3           4.0            6.0
case 4           5.0            4.0
case 5           6.0            7.0

[5 rows x 40 columns]

In [31]:
# -------------------
# Exporter tout votre code Python en HTML
# -------------------

# Votre code complet (copiez-collez tout ici)
code_complet = """
#import library 
import pandas as pd

#read csv file
df = pd.read_csv(
"C:/Users/Anaëlle/Desktop/Stage CHU/AKAKPOVI.ANAELLE/Soutenance_Python/data/REFLEXION.csv",
sep=","
)

#print results
print(df.head())
print(df.shape)
print(df.columns[:10])
print(df["sid"])

#remove index line 3 and reset/reinitialize index
df = df.drop(df.index[3]).reset_index(drop=True)

# select columns with "css" 
df_css = df.filter(regex='css', axis=1)

# show first lines
print(df_css.head())
# Remove columns with "rea" and columns finish by "css1"
df_css_clean = df_css.filter(regex='^(?!.*rea)(?!.*css1$)', axis=1)


# Keep columns that start with "v"              
df_v = df_css_clean.filter(regex='^v', axis=1)

# Remove columns "v" with cssforce1, cssforce2, cssforce3 or cssforcescref
df_v = df_v.filter(regex='^(?!.*cssforce([123]|scref)).*', axis=1)

# Reset index
df_v = df_v.reset_index(drop=True)

# Keep 3 columns "icsstemp_s", "icsssud_s", "icssforcemoy_s"
df_exceptions = df_css_clean.filter(items=["icsstemp_s", "icsssud_s", "icssforcemoy_s"])
df_exceptions = df_exceptions.reset_index(drop=True)

# Combine
df_css_clean = pd.concat([df_v, df_exceptions], axis=1)

#see results
print(df_css_clean.shape)
print(df_css_clean.columns)
print(df_css_clean.head())


#see clean table
df_css_clean
# New DataFrame for binarisation
binarisation = df_css_clean.copy()

# Select columns with "cssdoul"
colonnes_cssdoul = binarisation.filter(regex='cssdoul', axis=1).columns

# Apply binairy transformation : >=8 -> 1, <8 -> 0
binarisation[colonnes_cssdoul] = binarisation[colonnes_cssdoul].applymap(
    lambda x: 1 if x >= 8 else (0 if pd.notna(x) else pd.NA)
)
# Preview
print("Colonnes transformées en binaire :", list(colonnes_cssdoul))
print(binarisation[colonnes_cssdoul].head())
#csstemp already binarize
colonnes_csstemp = df_css_clean.filter(regex='csstemp', axis=1).columns
print(list(colonnes_csstemp))
# View five first lines csstemp
print(df_css_clean[colonnes_csstemp].head())
# Select columns with "csssud" to check values
colonnes_csssud = df_css_clean.filter(regex='csssud', axis=1).columns
print("Colonnes csssud :", list(colonnes_csssud))
# View five first lines
print(df_css_clean[colonnes_csssud].head())
#check data for "cssoed" already binarized

#Columns with cssoed
colonnes_cssoed = df_css_clean.filter(regex='cssoed', axis=1).columns
print("Colonnes cssoed :", list(colonnes_cssoed))

#view results
print("\nAperçu des colonnes cssoed :")
print(df_css_clean[colonnes_cssoed].head())

#check data for "forcemoy" 

# Columns "cssforcemoy"
colonnes_cssforcemoy = df_css_clean.filter(regex='cssforcemoy', axis=1).columns
print("Colonnes cssforcemoy :", list(colonnes_cssforcemoy))

#view results
print("\nAperçu des colonnes cssforcemoy :")
print(df_css_clean[colonnes_cssforcemoy].head())


#binarisation "sudation" and "force moyenne" 
# pathologic columns "csssud" 30% difference
colonnes_csssud = df_css_clean.filter(regex='^v.*_csssud$', axis=1).columns

# Binarisation 
binarisation_sud = ((df_css_clean[colonnes_csssud].sub(df_css_clean['icsssud_s'], axis=0)
                     .abs()
                     .div(df_css_clean['icsssud_s'], axis=0)) >= 0.3)

binarisation_sud = binarisation_sud.where(df_css_clean[colonnes_csssud].notna()).astype("Int64")

# view
print(binarisation_sud.head())

# pathologic columns "forcemoy"
colonnes_cssforcemoy = df_css_clean.filter(regex='^v.*_cssforcemoy$', axis=1).columns

# Binarisation 5kg difference
binarisation_forcemoy = ((df_css_clean[colonnes_cssforcemoy]
                          .sub(df_css_clean['icssforcemoy_s'], axis=0)
                          .abs()) >= 5)

binarisation_forcemoy = binarisation_forcemoy.where(df_css_clean[colonnes_cssforcemoy].notna()).astype("Int64")
# View
print(binarisation_forcemoy.head()) 
# Final table based on df_css_clean
df_binarise_final = df_css_clean.copy()

#replace pain columns by binary version 
df_binarise_final[colonnes_cssdoul] = binarisation[colonnes_cssdoul]

#replace "sudation" column by binary version
df_binarise_final[colonnes_csssud] = binarisation_sud

#replace "forcemoy" columns
df_binarise_final[colonnes_cssforcemoy] = binarisation_forcemoy

#delete healthy columns
df_binarise_final = df_binarise_final.drop(
    columns=["icsssud_s", "icssforcemoy_s", "icsstemp_s"],
    errors="ignore"
)

#view clean
df_binarise_final


#export to csv

#define index
df_binarise_final.index = [f"case {i+1}" for i in range(len(df_binarise_final))]

# name the index
df_binarise_final.index.name = "sid"

df_binarise_final.to_csv(
"C:/Users/Anaëlle/Desktop/Stage CHU/AKAKPOVI.ANAELLE/Soutenance_Python/data/df_binarise_final.csv",
sep=";",
encoding="utf-8-sig",
index=True
)
#open csv file df_binarise_final to check lines
df = pd.read_csv(
    "C:/Users/Anaëlle/Desktop/Stage CHU/AKAKPOVI.ANAELLE/Soutenance_Python/data/df_binarise_final.csv",
    sep=';' 
)
#print results
print(df.head())
print(df.shape) 

#create table for bland altman 
# copy data frame binarized
df_score = df_binarise_final.copy()

# final table for scores
df_scores = pd.DataFrame(index=df_score.index)

# new table for score 
df_scores = pd.DataFrame(index=df_binarise_final.index)

# Boucle on V1 à V20
for i in range(1, 21):

    # visit columns
    cols_v = df_binarise_final.filter(regex=f'^v{i}_').columns

    # Separate objectif / subjectif
    cols_obj = cols_v[:8]   # 8 premières colonnes
    cols_subj = cols_v[8:]  # 8 dernières colonnes

    # Calculate scores
    df_scores[f'V{i}_Scoreobj'] = df_binarise_final[cols_obj].sum(axis=1)
    df_scores[f'V{i}_Scoresubj'] = df_binarise_final[cols_subj].sum(axis=1)

# final result
print(df_scores.shape)
print(df_scores.head())

df_scores.to_csv(
"C:/Users/Anaëlle/Desktop/Stage CHU/AKAKPOVI.ANAELLE/Soutenance_Python/data/df_scores_final.csv",
sep=";",
encoding="utf-8-sig",
index=True
)
"""

# Chemin où enregistrer le fichier HTML
html_file = "C:/Users/Anaëlle/Desktop/Stage CHU/AKAKPOVI.ANAELLE/Soutenance_Python/code_complet.html"

# Générer le HTML
html_content = f"""
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>Code Python Complet</title>
<style>
body {{ font-family: monospace; background-color:#f5f5f5; padding:20px; }}
pre {{ background-color:#eee; padding:15px; border-radius:5px; overflow-x:auto; }}
</style>
</head>
<body>
<h2>Code Python Complet</h2>
<pre>{code_complet}</pre>
</body>
</html>
"""

# Sauvegarder
with open(html_file, "w", encoding="utf-8") as f:
    f.write(html_content)

print(f"✅ HTML généré : {html_file}")

✅ HTML généré : C:/Users/Anaëlle/Desktop/Stage CHU/AKAKPOVI.ANAELLE/Soutenance_Python/code_complet.html